export const MIN_USERNAME_LENGTH = 3;
export const MAX_USERNAME_LENGTH = 20;
export const MIN_DISPLAY_NAME_LENGTH = MIN_USERNAME_LENGTH;
export const MAX_DISPLAY_NAME_LENGTH = MAX_USERNAME_LENGTH;
export const MIN_PASSWORD_LENGTH = 8;

export const MAX_MESSAGE_LENGTH = 300;
